version: '3.8'

services:
  pppoe-monitor:
    build: .
    container_name: pppoe_monitor_app
    restart: always
    ports:
      - "5050:5000"
      - "514:514/udp"
    volumes:
      - ./instance:/app/instance
